services:
  devcontainer:
    container_name: BracyTech-DC
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
    env_file:
      - .env
    networks:
      - traefik
    # volumes:
    #   - ..:/${localWorkspaceFolder}:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

networks:
  traefik:
    external: true
